### ISSUE TITLE
Set the properties.yml file.

### ISSUE THREAD

**Issue by joshkim27** [neo-java/springboot_base#6]
Set the properties.yml file for spring-boot.

**Comment by ttobii** [comment]
maven의 profile 이 자연스럽게 spring.profile에 적용 될 수 있도록 설정
reousrce-${profile} 의 폴더 형태로 package 사이클인 경우 해당 폴더만 복사하여 package
${profile} 의 변수는 특수문자를 제거한 슬랙아이디로 설정됨
빌드 관련 사항이라 pom.xml 파일 수정이 불가피 하였음.

각자 해와야 할 작업들
- 각자 resource-${profile}  폴더 생성하여 자신의 profile 으로 빌드 및 패키지 확인하기
- IDE의 의존성이 적은 mvn spring-boot:run -P ${profile} 으로 실행 및 IDE 에 설정해보기
